import os
import sys
import importlib.util

sys.path.append(r"C:\Users\paulo\Desktop\balor")

# Load balor-svg.py
spec = importlib.util.spec_from_file_location("balor_svg", r"C:\Users\paulo\Desktop\balor\balor-svg.py")
balor_svg = importlib.util.module_from_spec(spec)

# Let's inspect the SVG file using svgpathtools directly to see its actual bbox
from svgpathtools import svg2paths2
paths, attributes, svg_attributes = svg2paths2(r"C:\Users\paulo\Desktop\balor\temp_workspace.svg")

min_x, max_x = float('inf'), float('-inf')
min_y, max_y = float('inf'), float('-inf')
for p in paths:
    bbox = p.bbox()
    min_x = min(min_x, bbox[0])
    max_x = max(max_x, bbox[1])
    min_y = min(min_y, bbox[2])
    max_y = max(max_y, bbox[3])

print(f"SVG raw paths BBox: X: [{min_x}, {max_x}], Y: [{min_y}, {max_y}]")

# Now let's see what coordinates are generated by rendering them
# We can mock the job's append method to log the coordinates
class MockJob:
    def __init__(self):
        self.operations = []
        self._travel_speed = 800
        self.position = 0
    def ready(self): pass
    def set_travel_speed(self, s): self._travel_speed = s
    def set_cut_speed(self, s): pass
    def set_power(self, p): pass
    def set_frequency(self, f): pass
    def raw_travel(self, x, y): pass
    
    def pos(self, x, y):
        # Return scaled values or just (x, y) for debugging
        return x, y
    
    def goto(self, x, y, jump_delay=None):
        self.operations.append(("goto", x, y))
        
    def draw_line(self, x0, y0, x1, y1, seg_size=5, Op=None):
        self.operations.append(("line", x0, y0, x1, y1))
        
    def laser_control(self, state): pass

# Run light mode render
mock_job_light = MockJob()
# We will temporarily replace render_stroke_light's calls
# Let's run a manual simulation of render_svg in light mode
# Let's see what args are needed
class MockArgs:
    operation = "light"
    xscale = 1.0
    yscale = 1.0
    xoff = 0.0
    yoff = 0.0
    segment_length = 1.0
    repetition = 1
    travel_speed = 800
    hidden_tags = ""

# Simulate light mode
min_lx, max_lx = float('inf'), float('-inf')
min_ly, max_ly = float('inf'), float('-inf')
for path in paths:
    # render_stroke_light logic
    num_points = int(round(path.length() / MockArgs.segment_length))
    if num_points < 2: num_points = 2
    import numpy as np
    ts = np.linspace(0, 1, num_points)
    points = [(c.real*MockArgs.xscale + MockArgs.xoff, -c.imag*MockArgs.yscale + MockArgs.yoff) for c in [path.point(t) for t in ts]]
    for x, y in points:
        min_lx = min(min_lx, x)
        max_lx = max(max_lx, x)
        min_ly = min(min_ly, y)
        max_ly = max(max_ly, y)

print(f"Simulated Light mode mm BBox: X: [{min_lx}, {max_lx}], Y: [{min_ly}, {max_ly}]")

# Simulate mark mode hatching
class MockSettings:
    def get(self, color):
        # frequency, power, speed, angle, spacing, pattern, repeats
        return (30.0, 80.0, 800.0, 45.0, 40.0, None, 10)

settings = MockSettings()
min_mx, max_mx = float('inf'), float('-inf')
min_my, max_my = float('inf'), float('-inf')

# Let's mock render_fill's coordinate generation
for path in paths:
    angle = 45.0
    spacing = 0.04
    rot_path = path.rotated(-angle)
    xmin, xmax, ymin, ymax = rot_path.bbox()
    hatch_x = np.linspace(xmin-0.1, xmax+0.1, int(round((0.2+xmax-xmin)/spacing)))
    import cmath
    from svgpathtools import Line
    for x in hatch_x:
        line = Line(complex(x, ymin-0.1), complex(x, ymax+0.1))
        try:
            base_intersects = rot_path.intersect(line)
        except ValueError:
            continue
        intersects = []
        for ((_,seg,t0), (_,_,t1)) in base_intersects:
            p0 = line.point(t1)
            intersects.append(p0.imag)
        intersects.sort()
        
        def rot_back(px, py):
            rad = np.radians(angle)
            c = complex(px, py) * cmath.rect(1, rad)
            return c.real, c.imag
            
        for y0, y1 in zip(intersects[::2], intersects[1::2]):
            rx0, ry0 = rot_back(x, y0)
            rx1, ry1 = rot_back(x, y1)
            px0 = rx0 * MockArgs.xscale + MockArgs.xoff
            py0 = -ry0 * MockArgs.yscale + MockArgs.yoff
            px1 = rx1 * MockArgs.xscale + MockArgs.xoff
            py1 = -ry1 * MockArgs.yscale + MockArgs.yoff
            
            min_mx = min(min_mx, px0, px1)
            max_mx = max(max_mx, px0, px1)
            min_my = min(min_my, py0, py1)
            max_my = max(max_my, py0, py1)

print(f"Simulated Mark mode mm BBox:  X: [{min_mx}, {max_mx}], Y: [{min_my}, {max_my}]")
